name: example
description: "Some example apps showing off the Sketchy Design Language for any Flutter platform."
publish_to: "none"

environment:
  sdk: ^3.10.0

dependencies:
  eliza_chat: ^1.0.0
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.12.0
  go_router: ^14.6.2
  google_fonts: ^6.3.2
  intl: ^0.20.2
  sketchy_design_lang:
    path: ../

dev_dependencies:
  all_lint_rules_community: ^0.0.38
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/
  fonts:
    - family: Excalifont
      fonts:
        - asset: assets/fonts/Excalifont-Regular.ttf
    - family: XKCD
      fonts:
        - asset: assets/fonts/xkcd-Regular.otf
