name: example
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2
  sketchy_design_lang:
    path: ../
  wired_elements:
    path: ../third_party/wired_elements

dev_dependencies:
  all_lint_rules_community: ^0.0.38
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: false
  assets:
    - assets/images/
