name: sketchy_design_lang
description: |-
  Sketchy is a hand-drawn, xkcd-inspired design language for Flutter on mobile,
  desktop, and web
version: 0.3.0
homepage: https://github.com/csells/sketchy_design_lang
repository: https://github.com/csells/sketchy_design_lang

environment:
  sdk: ^3.10.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  rough_flutter: ^0.1.2

dev_dependencies:
  all_lint_rules_community: ^0.0.38
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/
  fonts:
    - family: ComicShanns
      fonts:
        - asset: lib/fonts/comic-shanns-2.ttf
